"""
pipeline/schemas/models.py

Pydantic data contracts for every dataset in the pipeline.

These models serve as the formal schema at each layer boundary.
Any code that produces or consumes a dataset can validate against
the corresponding model — catching schema drift before it propagates.

Validation is intentionally strict: extra fields are forbidden and
required fields are required.  If a schema changes, the contract must
change first.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ─────────────────────────────────────────────────────────────────────────────
# Bronze (raw) schemas
# ─────────────────────────────────────────────────────────────────────────────

CHANNELS = Literal["web", "mobile", "marketplace"]
ORDER_STATUSES = Literal["pending", "processing", "shipped", "delivered", "cancelled", "returned"]
PAYMENT_METHODS = Literal["credit_card", "debit_card", "pix", "boleto", "wallet"]
PAYMENT_STATUSES = Literal["approved", "declined", "pending", "refunded"]


class CustomerRaw(BaseModel):
    """Raw customer record as generated by Faker."""

    model_config = {"extra": "forbid"}

    customer_id: int = Field(ge=1)
    name: str
    email: str
    phone: str
    city: str
    state: str = Field(min_length=2, max_length=2)
    birth_date: str
    created_at: str


class ProductRaw(BaseModel):
    """Raw product record."""

    model_config = {"extra": "forbid"}

    product_id: int = Field(ge=1)
    name: str
    category: str
    subcategory: str
    price: float = Field(gt=0)
    cost: float = Field(ge=0)
    stock_qty: int = Field(ge=0)
    created_at: str

    @model_validator(mode="after")
    def cost_must_not_exceed_price(self) -> "ProductRaw":
        """Validate cost ≤ price (margin ≥ 0).

        Returns:
            Validated model instance.

        Raises:
            ValueError: When cost exceeds price.
        """
        if self.cost > self.price:
            raise ValueError(f"cost ({self.cost}) must not exceed price ({self.price})")
        return self


class OrderRaw(BaseModel):
    """Raw order record."""

    model_config = {"extra": "forbid"}

    order_id: int = Field(ge=1)
    customer_id: int = Field(ge=1)
    order_date: str
    status: ORDER_STATUSES
    total_amount: float = Field(gt=0)
    shipping_fee: float = Field(ge=0)
    channel: CHANNELS


class OrderItemRaw(BaseModel):
    """Raw order-item record."""

    model_config = {"extra": "forbid"}

    item_id: int = Field(ge=1)
    order_id: int = Field(ge=1)
    product_id: int = Field(ge=1)
    quantity: int = Field(ge=1)
    unit_price: float = Field(gt=0)
    discount: float = Field(ge=0, le=1)
    line_total: float = Field(ge=0)


class PaymentRaw(BaseModel):
    """Raw payment record."""

    model_config = {"extra": "forbid"}

    payment_id: int = Field(ge=1)
    order_id: int = Field(ge=1)
    method: PAYMENT_METHODS
    status: PAYMENT_STATUSES
    amount: float = Field(gt=0)
    paid_at: str


class ReviewRaw(BaseModel):
    """Raw review record."""

    model_config = {"extra": "forbid"}

    review_id: int = Field(ge=1)
    order_id: int = Field(ge=1)
    customer_id: int = Field(ge=1)
    product_id: int = Field(ge=1)
    rating: int = Field(ge=1, le=5)
    comment: str
    created_at: str


# ─────────────────────────────────────────────────────────────────────────────
# Gold (dimensional) schemas
# ─────────────────────────────────────────────────────────────────────────────


class DimCliente(BaseModel):
    """Customer dimension record."""

    sk_cliente: int = Field(ge=1)
    nk_customer_id: str  # HMAC-hashed natural key
    city: str
    state: str
    dt_criacao: Optional[datetime]


class DimProduto(BaseModel):
    """Product dimension record."""

    sk_produto: int = Field(ge=1)
    nk_product_id: int = Field(ge=1)
    nm_produto: str
    category: str
    subcategory: str
    price: float = Field(gt=0)
    cost: float = Field(ge=0)
    margem_pct: float


class DimTempo(BaseModel):
    """Date dimension record."""

    sk_tempo: int = Field(ge=1)
    dt_data: date
    ano: int
    mes: int = Field(ge=1, le=12)
    dia: int = Field(ge=1, le=31)
    trimestre: int = Field(ge=1, le=4)
    semana_ano: int
    dia_semana: int = Field(ge=0, le=6)
    nm_dia_semana: str
    nm_mes: str
    fl_fimdesemana: bool
